apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pull-sign-push-pipeline-2-
  namespace: pull-sign-push-pipeline
spec:
  pipelineRef:
    name: pull-sign-push
  params:
    - name: pull-image
      value: ""
    - name: push-registry
      value: ""
    - name: registry-credential-secret
      value: ""
    - name: docker-config-secret
      value: "" 
    - name: image-name
      value: ""
    - name: cosign-key-secret
      value: ""
  serviceAccountName: pipeline
