apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pull-sign-push-pipeline-2-
  namespace: pull-sign-push-pipeline
spec:
  pipelineRef:
    name: pull-sign-push
  params:
    - name: pull-image
      value: "registry.access.redhat.com/ubi8/ubi:8.6-903.1661794351"
    - name: push-registry
      value: "quay.io"
    - name: user
      value: "rh_ee_castaffo"
    - name: pass
      value: rh-ee-castaffo-pull-secret
    - name: image-name
      value: "ubi:8.3-297"
  serviceAccountName: pipeline
  workspaces:
    - name: pull-sign-push-volume
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
        status: {}
