apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pull-sign-push-pipeline-2-
  namespace: pull-sign-push-pipeline
spec:
  pipelineRef:
    name: pull-sign-push
  params:
    - name: registry
      value: quay.io
    - name: user
      value: rh_ee_castaffo
    - name: pass
      value: rh-ee-castaff-pull-secret
    - name: image-name
      value: app-sre/ubi8-ubi-minimal
  workspaces:
    - name: pull-sign-push-volume
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
        status: {}
