apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pull-sign-push-volume
  namespace: pull-sign-push-pipeline
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Mi
    