# TODO: maybe tag it too?

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-image
  namespace: pull-sign-push-pipeline
spec:
  params:
    - name: image-to-pull
      description: the url to pull the image from
  steps:
    - name: buildah-pull
      image: quay.io/buildah/stable
      command: ["buildah"]
      args:
        - "pull"
        - "$(params.image-to-pull)"
      workingDir: /usr/var/containers
      securityContext:
        privileged: true
    - name: list-images
      image: quay.io/buildah/stable
      command: ['buildah']
      args:
        - 'images'
      workingDir: /usr/var/containers
      securityContext:
        privileged: true
  workspaces:
  - name: output
    mountPath: /output
