apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-sign-push
  namespace: pull-sign-push-pipeline
spec:
  params:
    - name: pull-image
      type: string
      description: full registry/image:tag for the image to pull
    - name: push-registry
      type: string
      description: url for the registry to push to (docker.io, quay.io, etc.)
    - name: registry-credential-secret
      type: string
      description: name of the secret that contains a 'user' and 'pass' that logs into the push registry
    - name: docker-config-secret
      type: string
      description: name of the secret that holds the user's docker config
    - name: push-image-name
      type: string
      description: name of the image to push
    - name: cosign-key-secret
      type: string
      description: name of the secret that holds the cosign private key and its password
  steps:
    - name: pull-sign-push
      env:
      - name: REGISTRY_USER
        valueFrom:
          secretKeyRef:
            name: $(params.registry-credential-secret)
            key: user
      - name: REGISTRY_PASS
        valueFrom:
          secretKeyRef:
            name: $(params.registry-credential-secret)
            key: pass
      - name: DOCKER_CONFIG
        valueFrom:
          secretKeyRef:
            name: $(params.docker-config-secret)
            key: config
      - name: COSIGN_KEY
        valueFrom:
          secretKeyRef:
            name: $(params.cosign-key-secret)
            key: key
      - name: COSIGN_KEY_PASS
        valueFrom:
          secretKeyRef:
            name: $(params.cosign-key-secret)
            key: password
      image: registry.access.redhat.com/ubi8/ubi:8.3-297
      script: |
        #!/usr/bin/env bash
        set +x

        yum install podman -y -q

        # install cosign
        yum install wget -y -q 
        wget "https://github.com/sigstore/cosign/releases/download/v1.6.0/cosign-linux-amd64" -q
        chmod +x cosign-linux-amd64

        echo "pull the image"
        podman pull $(params.pull-image)

        echo ""
        echo "tag the image"
        podman tag $(params.pull-image) $(params.push-registry)/${REGISTRY_USER}/$(params.push-image-name)

        echo ""
        echo "push the image"
        podman login --tls-verify=false -u ${REGISTRY_USER} -p ${REGISTRY_PASS} $(params.push-registry)
        podman push $(params.push-registry)/${REGISTRY_USER}/$(params.push-image-name) --remove-signatures

        echo ""
        echo "sign the image"
        echo -e ${COSIGN_KEY} > cosign.key
        echo ${DOCKER_CONFIG} > ~/.docker/config.json
        printf ${COSIGN_KEY_PASS} | ./cosign-linux-amd64 sign --verbose --key cosign.key $(params.push-registry)/${REGISTRY_USER}/$(params.push-image-name)

