# TODO: maybe tag it too?

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-image
  namespace: pull-sign-push-pipeline
spec:
  params:
    - name: image-to-pull
      description: the url to pull the image from
  steps:
    - name: hello-world1
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c", "echo Hello World 1!"]
    - name: log-name
      image: registry.access.redhat.com/ubi8/ubi:8.3-297
      command: ["/bin/bash"]
      args: ["-c", "echo $(params.image-to-pull)"]
    - name: buildah-pull
      image: quay.io/buildah/stable
      command: ['buildah', 'pull', '$(params.image-to-pull)']

  workspaces:
  - name: output
    mountPath: /

