apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image
  namespace: pull-sign-push-pipeline
spec:
  params:
    - name: registry
      type: string
      description: url for the registry to push to (docker.io, quay.io, etc.)
    - name: user
      type: string
      description: username for the registry account
    - name: pass
      type: string
      description: password for registry account
    - name: image-name
      type: string
      description: name of the image to push
  steps:
    - name: list-images
      image: quay.io/buildah/stable
      command: ['buildah']
      args:
        - 'images'
    - name: buildah-push
      image: quay.io/buildah/stable
      command: ['buildah']
      args:
        - 'push'
        - '--creds=$(params.user):$(params.pass)'
        - '--tls-verify=false'
        - '$(params.registry)/$(params.user)/$(params.image-name)'
        - 'docker://$(params.registry)/$(params.user)/$(params.image-name)'
      workingDir: /usr/var/containers
      securityContext:
        privileged: true
  workspaces:
    - name: input
      mountPath: /input