# TODO: maybe sign it too?

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-image
  namespace: pull-sign-push-pipeline
spec:
  params:
    - name: image_to_pull
      description: the url to pull the image from
  steps:
    - name: podman-pull
      env:
       - name: IMAGE_TO_PULL
         valueFrom:
           secretKeyRef:
             key: image_to_pull
             name: $(params.image_to_pull)
      image: registry.access.redhat.com/ubi8/ubi:8.3-297
      resources: {}
      script: >-
        #!/user/bin/env/bash
      
        yum install -y podman

        podman pull $IMAGE_TO_PULL

  workspaces:
  - name: pull-sign-push-volume
    mountPath: /

