# TODO: maybe tag it too?

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-image
  namespace: pull-sign-push-pipeline
spec:
  params:
    - name: image-to-pull
      description: the url to pull the image from
  steps:
    - name: buildah-pull
      image: quay.io/buildah/stable
      command: ['buildah', 'pull', $(params.image-to-pull)]

  workspaces:
  - name: pull-sign-push-volume
    mountPath: /

